name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Visit https://remotedesktop.google.com/headless & paste the authorization code'
        default: '4/0AfJohXmVnypAjauM6bgEV3vEzpA4tFGUAXms0iPy3IU3PHW0Bgn1_wdcgP-94rMZvTUKBg'
        required: true
      pincode:
        description: 'Enter a pin code'
        default: '123456'
        required: true
      authtoken:
        description: 'NGROK_AUTH_TOKEN'
        default: '1n391cGDskZaeIjGacWKh0NS93J_83n7ttgsiQJzVtV2R5nn1'
        required: true
      computername:
        description: 'MACHINE_NAME'
        default: 'ubuntu'
        required: true
      username:
        description: 'USER_NAME'
        default: 'user'
        required: true
      password:
        description: 'USER_PASSWORD'
        default: 'root'
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Mask Code & Pin
      run: |
        _Token=$(jq -r '.inputs.authtoken' $GITHUB_EVENT_PATH)
        _CName=$(jq -r '.inputs.computername' $GITHUB_EVENT_PATH)
        _Pass=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
        echo ::add-mask::$_Token
        echo ::add-mask::$_CName
        echo ::add-mask::$_Pass
        echo NGROK_TOKEN="$_Token" >> $GITHUB_ENV
        echo ComputerName="$_CName" >> $GITHUB_ENV
        echo Password="$_Pass" >> $GITHUB_ENV
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt install python3
        pip install lama-cleaner
    - name: Setting up Ngrok
      run:  bash Setup.sh "${{ env.NGROK_TOKEN }}" "${{ env.ComputerName }}" "${{ github.event.inputs.username }}" "${{ env.Password }}"
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3
    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}    
    - name: IP for Connect to your SSH
      run: bash Ip.sh "${{ github.event.inputs.username }}"
    - name: Keep Alive
      run: lama-cleaner --model=lama --device=cpu --port=8080
       
